#!/bin/bash

set -e
set -x

verbose=
#--verbose

[[ -d ./tmp/ ]] || mkdir ./tmp
ssh-add -L > ./tmp/authorized_keys
virt-builder $verbose \
     -o ./tmp/releaser.qcow2 \
     --format qcow2 \
     --arch amd64 \
     --size 20G \
     --commands-from-file virt-builder-commands \
     debian-9

