#!/bin/bash

set -x
set -e
set -o pipefail

remote=${remote:-releaser.local}
gpg_local_socket=$(gpgconf --list-dir agent-extra-socket)
gpg_remote_socket=$(ssh releaser@$remote gpgconf --list-dir agent-socket)

ssh -R $gpg_remote_socket:$gpg_local_socket releaser@$remote
