#!/bin/bash


function help {
    cat - <<EOF
Usage: $0 [option ...]

Generates a configuration file for LedgerSMB's release platform builder

Supported options:

  --defaults          pass this option to prevent this help text
                      when no options are required
  --force             overwrite existing configuration file
  --mail <address>    e-mail address to be used for git and
                      announcement mail 'From:'
  --mail-authmech     lists supported auth mechanisms
                      (default PLAIN LOGIN CRAM-MD5)
  --mail-host <name>  use named server as smarthost
  --mail-pass <pass>  use password 'pass' to authenticate with smarthost
  --mail-port <port>  use named port (on the smarthost) for sending mail
  --mail-starttls     use TLS (through STARTTLS) for sending mail
  --mail-tls          use TLS (but not STARTTLS) for sending mail
  --mail-notls        do not use TLS for sending mail
  --name <name>       name to be used for git and announcement
                      mail 'From:'
  --user <username>   username to be used for Docker, GitHub and Wikipedia

EOF

    exit 1
}

if [[ $# -eq 0 ]]
then
    help
fi

mail="rm@example.com"
name="Release Manager"
user="John"
mail_tls=yes
authmech="PLAIN LOGIN CRAM-MD5"
force=0
while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        --defaults)
            shift
            ;;
        --force)
            shift
            force=1
            ;;
        --git-mail)
            git_mail="$2"
            shift; shift;
            ;;
        --mail)
            mail="$2"
            git_mail=${git_mail:?${mail}}
            shift; shift;
            ;;
        --mail-authmech)
            authmech="$2"
            shift; shift;
            ;;
        --mail-host)
            mail_host="$2"
            shift; shift;
            ;;
        --mail-pass)
            mail_pass="$2"
            shift; shift;
            ;;
        --mail-port)
            mail_port="$2"
            shift; shift;
            ;;
        --mail-starttls)
            mail_tls=starttls;
            shift;
            ;;
        --mail-notls)
            mail_tls=no
            shift;
            ;;
        --mail-tls)
            mail_tls=tls;
            shift;
            ;;
        --name)
            name="$2"
            shift; shift;
            ;;
        --user)
            user="$2"
            shift; shift;
            ;;
        *)
            echo "Error: Unknown option $1"
            echo ""
            help
            ;;
    esac
done

if [ -f releaser.conf ] && [[ $force -eq 0 ]]
then
    echo "Can't overwrite existing configuration: no --force"
    exit 2
fi


# declare default values for configuration generation

declare -A conf=(
    [DockerUser]="$user"
    [DockerPassword]=None

    [EmailAUTHMECH]="$authmech"
    [EmailServer]="$mail_host"
    [EmailPort]="$mail_port"
    [EmailTLS]="$mail_tls"
    [EmailUser]="$user"
    [EmailPassword]="$mail_pass"
    [EmailFrom]="$name <$mail>"

    [GitUsername]="$name"
    [GitUsermail]="$mail"

    [GhcrToken]=None
    [GhcrUser]="$user"

    [GithubToken]=None
    [GithubUser]="$user"

    [MatrixPassword]=Doe
    [MatrixServer]="matrix.org"
    [MatrixUser]="$user"

    [SitePassword]=None

    [TransifexPassword]=None
    [TransifexToken]=None
    [TransifexUser]="$user"

    [WikipediaPassword]=Doe
    [WikipediaUser]="$user"
)

function generate_config {
    # generate config file
    for key in "${!conf[@]}"
    do
        val=$(echo ${conf[$key]} | sed -e 's/\(["'\''\`\$]\)/\\\1/g' )
        echo "conf[$key]=\"$val\""
    done | sort > releaser.conf
}



generate_config

cat - releaser.conf <<EOF
Configuration generated in 'releaser.conf' (adjust manually):

EOF
