#!/bin/bash

set -x
set -e
set -o pipefail

ssh-keygen -f "$HOME/.ssh/known_hosts" -R "releaser.local"
ssh-keyscan releaser.local >>~/.ssh/known_hosts

gpg_local_socket=$(gpgconf --list-dir agent-extra-socket)
gpg_remote_socket=$(ssh releaser@releaser.local gpgconf --list-dir agent-socket)

cat files/pubkey.asc | ssh releaser@releaser.local gpg --import
ssh releaser@releaser.local <<-EOF
set -xeo pipefail

# Docker, IPv6 and DNS resolution inside a VM don't seem to go well together
sudo bash -c "echo 1 >/proc/sys/net/ipv6/conf/all/disable_ipv6"
sudo service docker start
ssh-keyscan github.com > ~/.ssh/known_hosts
ssh-keyscan download.ledgersmb.org >> ~/.ssh/known_hosts
ssh-keyscan docs.ledgersmb.org >> ~/.ssh/known_hosts
touch ledgersmb-release-tools

rm -rf ledgersmb-release-tools
git clone git@github.com:ledgersmb/ledgersmb-release-tools

mkdir -p ~/bin
ln -sf ~/ledgersmb-release-tools/publish/release-ledgersmb ~/ledgersmb-release-tools/notify/release-notifications.sh ~/bin/

EOF

ssh -R $gpg_remote_socket:$gpg_local_socket releaser@releaser.local
