#!/bin/bash


virt-install \
    --import \
    --name releaser \
    --ram 8192 \
    --vcpus 6 \
    --graphics vnc \
    --disk path=./tmp/releaser.qcow2,bus=scsi \
    --network default,model=e1000 \
    --boot hd \
    --osinfo=debian12

virsh destroy releaser
virsh undefine releaser
