#!/bin/bash


virt-install \
    --import \
    --name releaser \
    --ram 2048 \
    --graphics vnc \
    --disk path=./tmp/releaser.qcow2,bus=virtio \
    --network default,model=virtio \
    --boot hd \
    --osinfo=debian11

virsh destroy releaser
virsh undefine releaser
