#!/usr/bin/ksh

set -x

release_version=$1
release_text=$(cat ~/ledgersmb-release-text | sed -e 's/"/\\"/g' | sed -e 's/\n/\\n/g')

if [[ ! -f ~/.lsmb-github-releases ]]; then
   fail "Missing configuration file ~/.lsmb-github-releases!"
else
   source ~/.lsmb-github-releases

   [[ -n "$github_user" ]] || fail "variable 'github_user' not defined! please define in ~/.lsmb-github-releases"
   [[ -n "$github_token" ]] || fail "variable 'github_token' not defined! please define in ~/.lsmb-github-releases"
fi


GH_api="https://api.github.com/repos/ledgersmb/LedgerSMB"
gh_auth="-u $github_user:$github_token"


tag_URL=$(curl "$GH_api/releases/tags/$release_version" | jq -M -r '.url')

curl -X PATCH $gh_auth $tag_URL -d "{ \"prerelease\": false, \"draft\": false, \"tag_name\": \"$release_version\", \"body\": \"$release_text\"}" | jq '.body'
